---
title: "ASTs_timing_trends"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=FALSE}
library(dplyr)
load(file = '~/Desktop/EHR/EHR-mining/UsefulDataForCleaning/data_path_name.Rdata')
load(file = paste0(data_path_name, '/ALL_clean_ASTs.Rdata'))

# RESULT_DELAY
astDF <- astDF %>% mutate(RESULT_DELAY = as.numeric(lubridate::as.duration(RESULT_DATE - ORDER_DATE)) / 86400)
x <- astDF$RESULT_DELAY
length(x[x < 1]) / length(x) * 100  # 0.03%
length(x[x > 60]) / length(x) * 100 # 0.51%
length(x[x > 5]) / length(x) * 100  # 11%
length(x[x > 14]) / length(x) * 100 # 1.8%
length(x[x > 30]) / length(x) * 100 # 0.94%
length(x[x > 60]) / length(x) * 100 # 0.5%

median(x) # 2.7
median(x[astDF$BLOOD]) # 3.6
length(x[!astDF$BLOOD][x[!astDF$BLOOD] > 5]) / length(x[!astDF$BLOOD]) * 100  # 8.9%
length(x[x > 5]) / length(x) * 100  # 11.1%
length(x[astDF$BLOOD][x[astDF$BLOOD] > 5]) / length(x[astDF$BLOOD]) * 100  # 34.8%
```


```{r echo=TRUE}
par(mfrow = c(2, 1), mar=c(4,3,2,1), mgp=c(2, 0.5, 0), tck=-0.015)
hist(x, xlim=c(0, 12), breaks=diff(range(x))*24, xlab='Days', main='Time between AST order and result - overall')
hist(x[astDF$BLOOD],  xlim=c(0, 12), breaks=diff(range(x[astDF$BLOOD]))*24, xlab='Days', main='Time between AST order and result - blood cultures')


# which bugs are responsible for the increased delay of blood cultures?
ecb <- astDF$RESULT_DELAY[astDF$BLOOD & astDF$BUG == 'Escherichia coli']
ec <- astDF$RESULT_DELAY[!astDF$BLOOD & astDF$BUG == 'Escherichia coli']
median(ec)  # 2.20
median(ecb) # 2.78
(median(ecb) - median(ec)) * 24 # ~14 hours
rm(ec, ecb)

sab <- astDF$RESULT_DELAY[astDF$BLOOD & astDF$BUG == 'Staphylococcus aureus']
sa <- astDF$RESULT_DELAY[!astDF$BLOOD & astDF$BUG == 'Staphylococcus aureus']
median(sa)  # 2.75
median(sab) # 3.16
(median(sab) - median(sa)) * 24 # ~10 hours
rm(sa, sab)



# WHICH BUGS?
t <- astDF %>% select(BUG, BLOOD) %>% table()
n <- 18
t <- t(head(t[order(t[,1], decreasing=TRUE), 2:1], n))
colnames(t) <- gsub('^([A-Z])[a-z]+ ([a-z]+)$', '\\1\\. \\2', colnames(t))
colnames(t)[colnames(t) == 'Coagulase Negative Staph'] <- 'Coag Neg Staph'
x <- barplot(rep(1,n), horiz=TRUE, plot=FALSE)
par(mfrow=c(1,1), mar=c(4, 8, 1, 2), mgp=c(2, 0.5, 0), tck=-0.015)
barplot(t, horiz=TRUE, names.arg=rep('', n), xlim=c(0,6e5), xlab='Number of isolate',
        legend.text = c('blood', 'non-blood'))
text(x=-10000, y=x, adj=c(1, 0.5), labels=colnames(t), xpd=NA)



num_year <- astDF %>%
   mutate(year = substr(ORDER_DATE,1,4)) %>%
   select(year) %>%
   table()
num_year <- num_year[-length(num_year)]

num_year_b <- astDF %>%
   filter(BLOOD) %>%
   mutate(year = substr(ORDER_DATE,1,4)) %>%
   select(year) %>%
   table()
num_year_b <- num_year_b[-length(num_year_b)]

par(mfrow=c(1,1), mar = c(4, 5.5, 1, 1), mgp=c(2.2, 0.6, 0), tck=-0.01)
plot(x = as.integer(names(num_year)), y = num_year, type = 'b', pch=16,
     xlab = 'Year', ylab='', yaxt='n')
title(ylab = 'Number of cultures', line=4)
points(x = as.integer(names(num_year_b)), y = num_year_b, type='b', pch=16, col='red')
axis(side = 2, at=c(11000, seq(0, 150000, 25000)), las=1, gap.axis=1e-11)
abline(h = 11000, lty=2)
legend('topleft', legend = c('overall', 'blood'), pch=16, lty=1, col=c('black', 'red'))





order_hour <- table(substr(astDF$ORDER_DATE, 12,13))
order_hour <- order_hour[names(order_hour) != '']
result_hour <- table(substr(astDF$RESULT_DATE, 12,13))
result_hour <- result_hour[names(result_hour) != '']
names(order_hour) <- gsub('^0', '', names(order_hour))
names(result_hour) <- gsub('^0', '', names(result_hour))
par(mfrow=c(1,2), mgp=c(2, 0.6, 0), mar=c(4, 3, 2, 1))
barplot(order_hour, main='AST orders', xlab = 'Hour of day', ylim=c(0, 27500))
barplot(result_hour, main='AST results', xlab = 'Hour of day', ylim=c(0, 27500))



# plotting bugs vs. year
if (FALSE) {
   # PLOT PREVALENCE OF BUGS/GENUS PER YEAR
   # BY GENUS
   bugs_year <- astDF %>%
      mutate(Genus = case_when(
         BUG == 'Coagulase Negative Staph' ~ 'Staphylococcus',
         grepl('Group [A-Z] Streptococci', BUG) ~ 'Streptococcus',
         grepl('Streptococc', BUG, ignore.case=TRUE) ~ 'Streptococcus',
         lengths(strsplit(BUG, ' ')) == 2L ~ gsub('^([A-Z][a-z]+) [a-z]+$', '\\1', BUG),
         grepl('.+ complex$', BUG) ~ gsub('^([A-Z][a-z]+) .+', '\\1', BUG)
      )) %>%
      filter(n() > 1000L, .by=Genus) %>%
      mutate(year = substr(ORDER_DATE,1,4)) %>%
      select(Genus, year) %>%
      table()
   colors <- c('#ffe119', '#4363d8', '#f58231', '#dcbeff', '#800000', '#000075', '#333333', '#888888', '#000000', '#911eb4')
   col_vec <- setNames(colors, rownames(bugs_year)); rm(colors)
   {
      pdf(file = '~/Desktop/EHR/EHR work/ALL/plots/GenusByYear.pdf', width = 10, height = 7.5)
      par(mar = c(2.5, 4, 1.5, 12), mgp = c(3, 0.4, 0), tck=-0.01)
      plot(NA, xlim=c(2014.8, 2023.2), ylim=c(100, 5000), log='y', yaxt='n', xaxt='n', xaxs='i',
           ylab = 'Number of isolates', xlab='',
           main = paste0('Prevalence of genus in blood cultures'))
      axis(side = 2, at = c(100, 200, 300, 500, 1000, 2000, 5000), las=1)
      axis(side = 2, at = seq(100, 4700, 200), labels=rep('', length(seq(100, 4700, 200))), tck=-0.005)
      axis(side = 1, at = 2015:2023)
      title(xlab = 'Year', line=1.5)
      for (b in seq_len(nrow(bugs_year))) {
         bug <- rownames(bugs_year)[b]
         bug_counts <- bugs_year[b,]
         lines(x=2015:2023, bug_counts, lwd=1.6, col=col_vec[bug])
      }
      text(x = 2023.3,
           y = bugs_year[,ncol(bugs_year)] + c('Candida' = 0, 'Enterobacter' = 0, 'Enterococcus' = 0, 'Escherichia' = 0, 
                                               'Klebsiella' = 50, 'Proteus' = 0, 'Pseudomonas' = 0, 'Serratia' = 0,
                                               'Staphylococcus' = 0, 'Streptococcus' = -30),
           labels = paste0(rownames(bugs_year), ' (n = ', format(rowSums(bugs_year), big.mark=','), ')'),
           xpd = NA,
           adj = 0,
           col = col_vec[rownames(bugs_year)])
      dev.off()
   }
   rm(b, bug, bug_counts, bugs_year, col_vec)
   
   # BY BUG
   topN <- 10
   common_bugs <- names(head(sort(table(astDF$BUG), decreasing = TRUE), n = topN))
   bug_by_year <- astDF %>%
      filter(BUG %in% common_bugs) %>%
      mutate(year = as.integer(substr(ORDER_DATE, 1, 4))) %>%
      filter(year %in% 2015:2023) %>%
      select(year, BUG) %>%
      table()
   years <- as.integer(rownames(bug_by_year))
   colnames(bug_by_year)[1] <- 'Coag. Neg. Staph.'
   colnames(bug_by_year)[2:ncol(bug_by_year)] <- gsub('([A-Z])[a-z]+ ([a-z]+)', '\\1. \\2', colnames(bug_by_year)[2:ncol(bug_by_year)])
   colors <- c('#ffe119', '#4363d8', '#f58231', '#dcbeff', '#800000', '#000075', '#a9a9a9', '#000000', '#fabed4', '#911eb4')
   col_vec <- setNames(colors, colnames(bug_by_year))
   {
      pdf(file = '~/Desktop/EHR/EHR work/ALL/plots/BugByYear.pdf', width = 10, height = 7.5)
      par(mar = c(2.5, 4, 1.5, 12), mgp = c(3, 0.4, 0), tck=-0.01)
      plot(NA, xlim=c(2014.8, 2023.2), ylim=c(140, 2500), log='y', yaxt='n', xaxt='n', xaxs='i',
           ylab = 'Number of isolates', xlab='',
           main = paste0('Prevalence of top ', topN, ' most common bugs in blood cultures'))
      axis(side = 2, at = c(200, 300, 400, 500, 1000, 2000), las = 1)
      axis(side = 2, at = seq(200, 2500, 100), labels=rep('', length(seq(200, 2500, 100))), tck=-0.005)
      axis(side = 1, at = seq(years[1],years[length(years)],1))
      title(xlab = 'Year', line=1.5)
      for (b in seq_len(ncol(bug_by_year))) {
         bug <- colnames(bug_by_year)[b]
         bug_counts <- bug_by_year[,b]
         lines(x = years, y = bug_counts, col=col_vec[bug], lwd=1.6)
      }
      text(x = 2023.3, y = bug_by_year[nrow(bug_by_year),]
           + c('CNS' = 22, 'faecalis' = 0, 'faecium' = -10, 'EC' = 0, 'KP' = 0, 'Pmir' = -28, 'PA' = 10, 'SA' = 0, 'Sepi' = 0, 'Shom' = -20),
           labels = paste0(names(col_vec), ' (n = ', format(colSums(bug_by_year), big.mark=','), ')'), 
           cex=1, xpd=NA, col=col_vec, adj = 0)
      dev.off()
   }
   rm(topN, common_bugs, years, b, bug, bug_counts, col_vec, colors, bug_by_year)
}




# determine proximity of subsequent cultures - do they cluster into encounters?
x <- astDF %>%
   group_by(PERSON_ID) %>%
   mutate(across(contains('DATE'), ~ as.Date(substr(., 1, 10)))) %>%
   mutate(DAYS_TO_NEXT_CULTURE = as.integer(lead(ORDER_DATE) - ORDER_DATE)) %>%
   ungroup() %>%
   select(DAYS_TO_NEXT_CULTURE) %>%
   unlist()
x <- x[!is.na(x)]
mean(x)
median(x)
range(x)
sum(x == 0, na.rm=T) / length(x)
sum(x == 1, na.rm=T) / length(x)
par(mfrow = c(2, 1), mgp=c(2, 0.5, 0), tck=-0.015)
hist(x, breaks=diff(range(x)), ylim=c(0, 2000), xlim=c(0, 365))
abline(v = 7)
barplot(table(x)[1:30])
```













