---
title: "CombinedASTsAbxAdminWIDE"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=FALSE, message=FALSE}
library(dplyr)
load(file = '~/Desktop/EHR/EHR-mining/UsefulDataForCleaning/data_path_name.Rdata')
load(file = '~/Desktop/EHR/EHR-mining/UsefulDataForCleaning/antibiotic_names/abbr_named.Rdata')
load(file = paste0(data_path_name, 'ASTs_AbxAdmin_blood_2017_2023.Rdata'))




# Course sizes
makePlot <- function(d, main='', targ=FALSE) {
   x <- empDF[[paste0('EMPIRIC', d)]][empDF$DELAY > d]
   if (targ) x <- empDF$TARGETED
   n <- sum(empDF$DELAY > d)
   x <- table(lengths(x)) / n
   x <- c(x[names(x) %in% as.character(0:2)], sum(x[!names(x) %in% as.character(0:2)]))
   names(x)[names(x) == ''] <- '>=3'
   b <- barplot(x, plot=F)
   barplot(x, ylim=c(0, 1), xlab='Number of antibiotics', main=paste0(main, ' (n = ', prettyNum(n, big.mark=','), ')'), yaxt='n')
   axis(side=2, las=1)
   text(x = b, y = x+0.05, labels=paste0(round(x, 3) * 100, '%'))
}
par(mfrow=c(2,2), oma=c(4,0,0,0), mar=c(4, 3, 2, 1), mgp=c(1.75, 0.5, 0), tck=-0.015)
makePlot(0, 'day of order')
makePlot(1, '1 day after order')
makePlot(2, '2 days after order')
makePlot(0, 'Day of result', targ=TRUE)
```




```{r, fig.height=2.75, fig.width=7, echo=FALSE}
# Empiric course and course size
makeBarplot <- function(main='') {
   n <- 8
   b <- barplot(rep(1, n), horize=T, plot=F)
   x <- empDF$EMPIRIC0
   if (grepl('whole', main))  x <- unlist(sapply(x, function(x) paste(abbr[x], collapse='+')))
   if (grepl('single', main)) x <- abbr[unlist(x)]
   h <- head(sort(table(x), decreasing = TRUE) / nrow(empDF), n)
   names(h)[names(h) == ''] <- 'No abx'
   barplot(h, horiz=TRUE, names.arg=NA, xlim=c(0,0.5), xpd=NA, main=main)
   axis(side=2, at=b, labels=names(h), las=1, tick=F, xpd=NA)
   text(x = h + 0.01, y = b, adj = 0, xpd=NA, labels = paste0(round(h,3)*100, '%'))
}
makePlot <- function(d, main='', targ=FALSE) {
   x <- empDF[[paste0('EMPIRIC', d)]][empDF$DELAY > d]
   if (targ) x <- empDF$TARGETED
   n <- sum(empDF$DELAY > d)
   x <- table(lengths(x)) / n
   x <- c(x[names(x) %in% as.character(0:2)], sum(x[!names(x) %in% as.character(0:2)]))
   names(x)[names(x) == ''] <- '>=3'
   b <- barplot(x, plot=F)
   barplot(x, ylim=c(0, 1), xlab='Number of antibiotics', yaxt='n',
           main=main)
   axis(side=2, las=1)
   text(x = b, y = x+0.05, labels=paste0(round(x, 3) * 100, '%'))
}
par(mfrow=c(1,3), mgp=c(1.75,0.5,0), tck=-0.015)
par(mar=c(4, 3, 2.5, 1))
makePlot(0, 'Empiric course size')
par(mar=c(2.5, 4, 2.5, 0.5))
makeBarplot(main='Empiric course (whole)')
makeBarplot(main='Empiric course (single)')



# Does empiric course depend upon gram-stain?

```





```{r, fig.height=4, fig.width=6}
# Course sizes bigger for mult-blood infections?
makeBarplot <- function(x, main='') {
   t <- table(empDF$MULT_BLOOD_ISO, lengths(x))
   t <- t(apply(t, 1, function(x) x / sum(x) * 100))
   rownames(t)[rownames(t) == 'TRUE'] <- 'multiple'
   rownames(t)[rownames(t) == 'FALSE'] <- 'single'
   barplot(t, beside=TRUE, main=main, leg=TRUE, args.legend=list(title='# isolates'), ylab='%', xlab='# of antibiotics')
}
par(mfrow=c(1,1), mar=c(5,5,3,3))
makeBarplot(x=empDF$TARGETED, main='Targeted course sizes')
makeBarplot(x=empDF$EMPIRIC0, main='Empiric0 course sizes')
makeBarplot(x=empDF$EMPIRIC1, main='Empiric1 course sizes')




```