---
title: "CombinedASTsAbxAdminWIDE"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=FALSE, message=FALSE}
library(dplyr)
load(file = '~/Desktop/EHR/EHR work/RdataFiles/ASTs_AbxAdmin_blood_2017_2023_imputed_encs_flagged_WIDE_survival.Rdata')
load(file = '~/Desktop/EHR/EHR-mining/UsefulDataForCleaning/antibiotic_names/abbr_named.Rdata')
abbr <- c(abbr, setNames('No abx', 'No abx'))


# Course sizes
makePlot <- function(d, main='', targ=FALSE) {
   x <- empDF[[d]]
   n <- nrow(empDF)
   x <- table(lengths(x)) / n
   x <- c(x[names(x) %in% as.character(0:3)], sum(x[!names(x) %in% as.character(0:3)]))
   names(x)[names(x) == ''] <- '>=4'
   b <- barplot(x, plot=F)
   barplot(x, ylim=c(0, 1), xlab='Number of antibiotics', main=main, yaxt='n')
   axis(side=2, las=1)
   text(x = b, y = x+0.05, labels=paste0(round(x, 3) * 100, '%'))
}
par(mfcol=c(2,3), oma=c(4,0,0,0), mar=c(4, 3, 2, 1), mgp=c(1.75, 0.5, 0), tck=-0.015)
makePlot('ABX_EMPp', '< 48h before order')
makePlot('ABX_EMP', 'Empiric (-48h, +12h)')
makePlot('ABX_BTW', '[12 hrs after order, before result]')
makePlot('ABX_TAR', 'Targeted')
makePlot('ABX_TARe', 'early Targeted')
makePlot('ABX_TARl', '>3 days after result')
```




```{r, fig.height=2.75, fig.width=7, echo=FALSE}
# Empiric course and course size
makeBarplot <- function(main='', side) {
   if (side == 'left')  par(mar=c(2.5, 8, 2.5, 0.5))
   if (side == 'right') par(mar=c(2.5, 6, 2.5, 2.5))
   n <- 8
   b <- barplot(rep(1, n), horize=T, plot=F)
   x <- empDF$ABX_EMP
   x[lengths(x) == 0L] <- 'No abx'
   if (grepl('whole', main))  x <- unlist(sapply(x, function(x) paste(abbr[x], collapse='+')))
   if (grepl('single', main)) x <- abbr[unlist(x)]
   h <- head(sort(table(x), decreasing = TRUE) / nrow(empDF), n)
   names(h)[names(h) == ''] <- 'No abx'
   barplot(h, horiz=TRUE, names.arg=NA, xlim=c(0,0.5), xpd=NA, main=main)
   axis(side=2, at=b, labels=names(h), las=1, tick=F, xpd=NA)
   text(x = h + 0.01, y = b, adj = 0, xpd=NA, labels = paste0(round(h,3)*100, '%'))
}

par(cex.main=1, mfrow=c(1,2), mgp=c(1.75,0.5,0), tck=-0.015)
makeBarplot(main='Empiric course (whole)', side='left')
makeBarplot(main='Empiric course (single)', side='right')


# Does empiric course depend upon gram-stain?
n <- 8
b <- barplot(rep(1, n), horize=T, plot=F)
makeBarplot <- function(bug = '', side='') {
   if (side == 'left')   par(mar=c(2.5, 8, 2.5, 0.5))
   if (side == 'middle') par(mar=c(2.5, 7, 2.5, 1.5))
   if (side == 'right')  par(mar=c(2.5, 6, 2.5, 2.5))
   if (side =='') par(mar = c(2.5, 4.5, 2.5, 0))
   if (bug == 'Gram negatives') {
      x <- empDF$ABX_EMP[grep('Klebsiella|Escherichia|Acinetobacter|Citrobacter|Enterobacter|Morganella|Serratia|Proteus|Pseudomonas', empDF$BUG)]
   } else if (bug == 'Gram positives') {
      x <- empDF$ABX_EMP[grep('Enterococ|Streptoc|Staph', empDF$BUG)]
   } else {
      x <- empDF$ABX_EMP[grep(bug, empDF$BUG)]
   }
   x[lengths(x) == 0L] <- 'No abx'
   x <- abbr[unlist(x)]
   #x <- sapply(x, function(a) paste(abbr[a], collapse='+'))
   h <- head(sort(table(x), decreasing = TRUE) / length(x), n)
   barplot(h, horiz=TRUE, names.arg=NA, xlim=c(0,0.5))
   axis(side=2, at=b, labels=names(h), las=1, tick=F)
   title(main=paste0(bug, ' (n = ', prettyNum(length(x), big.mark=','), ')'), line=0.25, xpd=NA)
   text(x = h + 0.01, y = b, adj = 0, xpd=NA,
        labels = paste0(round(h,3)*100, '%'))
}

# mar=c(2.5, 6, 2.5, 2.5)
par(mfrow=c(1,2), mgp=c(1.75,0.5,0), tck=-0.015)
makeBarplot('Gram positives', 'left')
makeBarplot('Gram negatives', 'right')

par(mfrow=c(1, 3), mar=c(2.5, 6.5, 1.5, 1), mgp=c(1.25,0.4,0), tck=-0.015)
makeBarplot('Streptococcus')
makeBarplot('Staphylococcus aureus')
makeBarplot('Enterococcus faecalis')

makeBarplot('Escherichia coli')
makeBarplot('Klebsiella pneumoniae')
makeBarplot('Pseudomonas aeruginosa')
```





```{r, fig.height=4, fig.width=7.5}
# Course sizes bigger for mult-blood infections?
empDF <- empDF %>%
   group_by(PERSON_ID, ORDER_DAY) %>%
   mutate(MULT_BLOOD_ISO = n() > 1L)

makeBarplot <- function(x, main='') {
   t <- table(empDF$MULT_BLOOD_ISO, lengths(x))
   t <- t(apply(t, 1, function(x) x / sum(x) * 100))
   rownames(t)[rownames(t) == 'TRUE'] <- 'multiple'
   rownames(t)[rownames(t) == 'FALSE'] <- 'single'
   barplot(t, ylim=c(0,40), beside=TRUE, main=main, leg=TRUE, args.legend=list(title='# blood isolates'), ylab='%', xlab='# of antibiotics')
}
par(mfrow=c(1,2), mar=c(5,3,3,3))
makeBarplot(x=empDF$ABX_EMP, main='Empiric course sizes')
makeBarplot(x=empDF$ABX_TAR, main='Targeted course sizes')
```


