---
title: "TargetedTherapies"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=FALSE, message=FALSE, fig.height=4.5, fig.width=10}
library(dplyr)
load(file = '~/Desktop/EHR/EHR work/RdataFiles/ASTs_AbxAdmin_blood_2017_2023_imputed_encs_flagged_WIDE_survival.Rdata')
#empDF <- empDF %>% filter(substr(ORDER_DAY, 1, 4) %in% as.character(2020:2023))
load(file = '~/Desktop/EHR/EHR-mining/UsefulDataForCleaning/antibiotic_names/abbr_named.Rdata')
abbr <- c(abbr, setNames('No abx', 'No abx'))
abbr <- c(abbr, setNames('ESBL', 'ESBL'))
source('~/Desktop/WrightLab/UsefulRfuncs/heatmap_new.R')

cex <- 0.9
par(cex.main=cex, cex.lab=cex, cex.axis=cex, cex=cex)


# note which are multi-clonal cultures
empDF <- empDF %>%
   group_by(PERSON_ID, ORDER_DAY) %>% 
   mutate(MULT_BLOOD_ISO = n() > 1L) %>%
   ungroup()

common_drugs <- names(head(sort(table(unlist(empDF$ABX_TAR)), decreasing=TRUE), n=24))
common_drugs <- unname(abbr[common_drugs])
set.seed(123L)
col_vec <- setNames(colors(distinct = TRUE)[sample(seq_along(colors(distinct=TRUE)), size=length(common_drugs))],
                    common_drugs)

empDF <- empDF %>% mutate(NO_TRT = lengths(ABX_EMPp) == 0L & lengths(ABX_EMP) == 0L & lengths(ABX_EMPr) == 0 & lengths(ABX_BTW) == 0L & lengths(ABX_TAR) == 0L & lengths(ABX_TARl) == 0L)
empDF <- empDF %>% mutate(NO_PRE_TAR = lengths(ABX_EMPr) == 0 & lengths(ABX_EMP) == 0L & lengths(ABX_BTW) == 0L)
empDF$TARG_ABBR <- sapply(empDF$ABX_TAR, function(x) paste(abbr[x], collapse='+'))


makeBarplot <- function(bug, drug=character(), status=NULL, xmax, remove_no_prior_abx=FALSE, leg=FALSE) {
   if (length(drug) == 2L) {
      w <- intersect(which(empDF$BUG==bug), intersect(which(empDF[[drug[1]]]==status[2]), which(empDF[[drug[2]]]==status[2])))
      resistance_phenotype <- paste(paste(abbr[drug], '-', ifelse(status==1L, 'R', 'S'), sep=''), collapse=' / ')
   } else if (length(drug) == 1L) {
      w <- intersect(which(empDF$BUG==bug), which(empDF[[drug]]==status))
      if (length(w) == 0L) {
         plot.new()
         return()
      }
      resistance_phenotype <- paste0(abbr[drug], '-', ifelse(status==1L, 'R', 'S'))
      if (drug == 'ESBL') {
         if (status == 1L) resistance_phenotype <- 'ESBL-producer'
         if (status == 0L) resistance_phenotype <- 'not ESBL-producer'
      }
   } else if (length(drug) == 0L) {
      w <- which(empDF$BUG == bug)
      resistance_phenotype <- bug
   }
   
   x <- empDF$TARG_ABBR[w]
   w_died <- which(empDF$DEATH_DATE[w] < empDF$RESULT_DAY[w])
   w_disch <- which(empDF$DISCHARGE_DAY[w] < empDF$RESULT_DAY[w] & x == '')
   w_disch <- setdiff(w_disch, w_died)
   w_noEnc <- which(is.na(empDF$ADMIT_DAY[w]) & x == '')
   x[w_died] <- 'Deceased'
   x[w_disch] <- 'Discharged'
   x[w_noEnc] <- 'Not inpatient'
   w_noAbx <- which(x == '')
   x[w_noAbx] <- 'Inpatient'
   w_excluded <- union(union(w_died,  w_noAbx),
                       union(w_disch, w_noEnc))
   
   total <- length(x)
   num_treated <- length(x[-w_excluded])
   
   t0 <- strsplit(x[-w_excluded], '+', fixed=TRUE)
   t0 <- sort(table(unlist(t0)), decreasing = TRUE)
   num_abx <- 10
   t <- head(t0, num_abx)
   t <- c(t, table(x[w_excluded]))
   abx_names <- names(t)
   abx_nums <- unname(t)
   t <- sapply(seq_along(t), function(i) {
      tab <- table(grepl('+', x[grep(names(t)[i], x)], fixed=TRUE))
      if (length(tab) == 2L) return(tab)
      if (length(tab) == 1L & names(tab) == 'TRUE') return(c('FALSE'=0L, tab))
      if (length(tab) == 1L & names(tab) == 'FALSE') return(c(tab, 'TRUE'=0L))
   })
   t <- t[2:1,]
   colnames(t) <- abx_names
   rownames(t)[rownames(t) == 'FALSE'] <- 'Mono'
   rownames(t)[rownames(t) == 'TRUE'] <- 'Combin.'
   t <- t / total * 100
   abx_pos <- colSums(t)
   
   b <- barplot(t, horiz=TRUE, xlim=c(0, xmax), xlab='', yaxt='n', leg=leg,
                space = c(rep(0.1, num_abx), 0.4, rep(0.1, ncol(t) - num_abx - 1)))
   bug_abbr <- gsub('([A-Z])[a-z]+ ([a-z]+)', '\\1. \\2', bug)
   title(main=paste0(bug, ' - ', resistance_phenotype, ' (n = ', total, ')'), line=0.5, font.main=4)
   title(xlab='% of infections')
   #text(x=abx_pos+0.75, y=b, adj=0, labels=paste0(round(colSums(t)), '%'))
   text(x=abx_pos+0.75, y=b, adj=0, labels=abx_nums)
   text(x=-0.75, y=b, adj=1, labels=abx_names, xpd=NA)
}


makeBugPlot <- function(bug, drug, status=list(0,1), xmax=70) {
   #layout(matrix(c(1,1,2,3), byrow=T, nrow=2))
   par(mfrow=c(1,2), oma=c(2,0,1,0), mgp=c(1.5, 0.3, 0), tck=-0.015)
   #par(mar=c(2.5, 8, 3, 8))
   #makeBarplot(bug=bug, xmax=xmax, leg=TRUE)
   par(mar=c(2.5, 7, 3, 3))
   makeBarplot(bug=bug, drug=drug, status=status[[1]], xmax=xmax, leg=TRUE)
   par(mar=c(2.5, 4, 3, 6))
   makeBarplot(bug=bug, drug=drug, status=status[[2]], xmax=xmax, leg=TRUE)
}


makeBugPlot(bug='Enterococcus faecium', drug=c('VANCOMYCIN', 'AMPICILLIN'), status=list(c(0,0), c(1,1)))
makeBugPlot('Staphylococcus aureus', 'OXACILLIN')
makeBugPlot('Escherichia coli', drug='ESBL')
makeBugPlot('Klebsiella pneumoniae', drug='ESBL')
makeBugPlot('Pseudomonas aeruginosa', drug='CEFEPIME')
makeBugPlot('Serratia marcescens', drug='ESBL')
makeBugPlot('Enterobacter cloacae', drug='ESBL')
```


# Heatmaps of definitive therapies
Along the *diagonal is monotherapy* with the indicated drug
Off-diagonal cells indicate combination therapy and include instances where the two indicated antibiotics were used alongside a third, fourth, etc.

```{r echo=FALSE, message=FALSE, fig.height=5.5, fig.width=10}
############# HEATMAPS ################
hm_plot <- function(bug, drug, status) {
   w <- which(empDF$BUG == bug & empDF[[drug]] == status)
   df <- empDF[w,]
   
   abx <- tail(sort(table(unlist(df$ABX_TAR))), n=8)
   abx <- names(abx[abx > 0.05 * max(abx)])
   
   mat <- matrix(NA, nrow=length(abx), ncol=length(abx), dimnames=list(abx, abx))
   
   for (r in seq_len(nrow(mat))) {
      r_w <- grep(abx[r], df$ABX_TAR)
      for (c in seq_len(ncol(mat))) {
         if (r == c) val <- sum(lengths(df$ABX_TAR[r_w]) == 1)
         if (r != c) val <- length(intersect(r_w, grep(abx[c], df$ABX_TAR)))
         mat[r, c] <- val
      }
   }
   
   rownames(mat) <- abbr[rownames(mat)]
   colnames(mat) <- abbr[colnames(mat)]
   
   plot_heatmap(mat, upper_only=TRUE,
                cols=colorRampPalette(c('white', '#D03326'))(max(mat)))
   title(main=paste0(abbr[drug], '-', ifelse(status==0, 'S', 'R')), cex.main=1)
}

makeHeatmap <- function(bug, drug) {
   hm_plot(bug, drug, 0)
   hm_plot(bug, drug, 1)
   mtext(text=bug, font=4, outer=TRUE, line=-1, cex=1)
}


par(mfrow=c(1,2), oma=c(3,0,0,0))
makeHeatmap(bug='Enterococcus faecium', drug='VANCOMYCIN')
makeHeatmap('Staphylococcus aureus', 'OXACILLIN')
makeHeatmap('Escherichia coli', drug='ESBL')
makeHeatmap('Klebsiella pneumoniae', drug='ESBL')
makeHeatmap('Pseudomonas aeruginosa', drug='CEFEPIME')
makeHeatmap('Serratia marcescens', drug='ESBL')
makeHeatmap('Enterobacter cloacae', drug='ESBL')
```





```{r}
# makeLinePlot <- function(bug, drug, status, abx) {
#    if (length(drug) == 2L) {
#       w <- intersect(which(empDF$BUG==bug), intersect(which(empDF[[drug[1]]]==status[2]), which(empDF[[drug[2]]]==status[2])))
#       resistance_phenotype <- paste(paste(abbr[drug], '-', ifelse(status==1L, 'R', 'S'), sep=''), collapse=' / ')
#    } else if (length(drug) == 1L) {
#       w <- intersect(which(empDF$BUG==bug), which(empDF[[drug]]==status))
#       resistance_phenotype <- paste0(abbr[drug], '-', ifelse(status==1L, 'R', 'S'))
#    }
#    num_per_year <- table(as.integer(substr(empDF$ORDER_DAY[w], 1, 4)))
#    w <- sapply(abx, function(x) w[grep(x, empDF$TARG_ABBR[w])])
#    y <- sapply(w, function(i) as.integer(substr(empDF$ORDER_DAY[i], 1, 4)))
#    t <- lapply(y, function(y) table(y))
#    for (i in seq_along(t)) {
#       if (length(t[[i]]) < 7) {
#          missing_years <- (2017:2023)[which(!as.character(2017:2023) %in% names(t[[i]]))]
#          t[[i]] <- c(t[[i]], setNames(rep(0,length(missing_years)), missing_years))
#          t[[i]] <- t[[i]][order(as.integer(names(t[[i]])))]
#       }
#       t[[i]] <- t[[i]] / num_per_year
#    }
#    
#    plot(NA, xlim=c(2017, 2023), ylim=c(0, max(sapply(t, max))), ylab='Proportion', xlab='Year', main=resistance_phenotype)
#    for (i in seq_along(t))
#       lines(x=2017:2023, y=t[[i]], col=col_vec[names(t[i])], lwd=2)
#    legend('topright', inset=c(-0.325, 0), legend=abx, col=col_vec[names(t)], lwd=2, xpd=NA, bty='n')
# }
```




